name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-daily:noble
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install python3-minimal
        sudo apt build-dep .
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test
      run: | 
        sudo ./scripts/github-ci-lxd-setup.sh
        sudo ./scripts/test-in-lxd.sh ${{ matrix.image }} "sudo apt-get update && sudo apt-get --assume-yes build-dep . && apt-get install --assume-yes tox && tox"
    - name: Build
      run: |
        python3 setup.py build_ext -i
